services:
  - type: web
    name: task1-beginner-profile-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_ORIGIN
        value: https://task1-beginner-profile-frontend-aedxqfb1e-roxyross-projects.vercel.app
